import os

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

LINE_WIDTH = 2

# ASTEROIDS
ASTEROID_MIN_RADIUS = 18
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MAX_SPEED = 100

# PLAYER/SHOOTER
PLAYER_RADIUS = 20
PLAYER_MAX_SPEED = 400  # px/s
PLAYER_ROTATE_SPEED = 250  # deg/s
PLAYER_ACCELERATION = 1000  # thrust
PLAYER_DRAG = 0.8  # allows some drift
PLAYER_FRICTION = 0.1
PLAYER_SHOOT_SPEED = 500  # px/s
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.25
SHOT_LIFESPAN = 2.0  # seconds
SHOT_RADIUS = 3

# COLLISION
PARTICLE_LIFESPAN = 0.5  # seconds

# COLORS
RED = (173, 43, 3)
ORANGE = (255, 165, 0)
BLUE = (13, 136, 189)
WHITE = (255, 255, 255)
LIGHT_GRAY = (204, 204, 204)
BLACK = (0, 0, 0)

SCREEN_COLOR = BLACK
STAR_COLORS = [(160, 160, 160), (184, 184, 184), (208, 208, 208), (231, 231, 231), WHITE]
ASTEROID_COLORS = [(50, 50, 50), (60, 60, 60), (70, 70, 70), (80, 80, 80), (90, 90, 90)]
PLAYER_COLOR = BLUE
THRUSTER_COLOR = ORANGE
SHOT_COLORS = [RED, (194, 74, 2), (214, 104, 2), (235, 135, 1), ORANGE]
PARTICLE_COLORS = SHOT_COLORS + [BLUE]
SCORE_COLOR = BLUE
WAVE_COLOR = WHITE
OVERLAY_COLOR = BLACK
GAME_OVER_COLOR = RED
FINAL_SCORE_COLOR = BLUE
PROMPT_COLOR = LIGHT_GRAY

# FILE PATHS
_BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FONT_REGULAR = os.path.join(_BASE_DIR, "assets", "fonts", "font_regular.otf")
FONT_SCORE = os.path.join(_BASE_DIR, "assets", "fonts", "font_score.ttf")
FONT_TITLE = os.path.join(_BASE_DIR, "assets", "fonts", "font_title.ttf")
LOG_DIR = os.path.join(_BASE_DIR, "logs")
LOG_GAME_STATE = os.path.join(LOG_DIR, "game_state.jsonl")
LOG_GAME_EVENTS = os.path.join(LOG_DIR, "game_events.jsonl")
HIGH_SCORES_FILE = os.path.join(_BASE_DIR, "logs", "high_scores.json")
